export default [
    {
      id: '1',
      data: { label: 'Year 1' },
      type: 'year',
      position: { x: 250, y: 25 },
      style: { backgroundColor: '#587B7F', color: 'white' },
    },
    {
      id: '2',
      data: { label: 'Introduction to Computer Engineering' },
      type: 'subject',
      position: { x: 100, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: '3',
      data: { label: 'Digital Logic Circuits' },
      type: 'subject',
      position: { x: 250, y: 250 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: '4',
      data: { label: 'Year 2' },
      type: 'year',
      position: { x: 260, y: 30 },
      style: { backgroundColor: '#587B7F', color: 'white' },
    },
    {
      id: '5',
      data: { label: 'Automata' },
      type: 'subject',
      position: { x: 250, y: 250 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: '6',
      data: { label: 'Year 3' },
      type: 'year',
      position: { x: 250, y: 250 },
      style: { backgroundColor: '#587B7F', color: 'white' },
    },
    {
      id: '7',
      data: { label: 'Probability and Random Process' },
      type: 'subject',
      position: { x: 250, y: 250 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: '8',
      data: { label: 'Seminar in Software' },
      type: 'subject',
      position: { x: 250, y: 250 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: '9',
      data: { label: 'Seminar in Computer Engineering' },
      type: 'subject',
      position: { x: 250, y: 250 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: '10',
      data: { label: 'Computer Security' },
      type: 'subject',
      position: { x: 250, y: 250 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: '11',
      data: { label: 'Introduction to Real Time System' },
      type: 'subject',
      position: { x: 250, y: 250 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
  ];
  