export default [
    {
      id: 'y-1',
      data: { label: 'Year 1' },
      type: 'input',
      position: { x: 137, y: 255 },
      style: { backgroundColor: '#587B7F', color: 'white', border: 'none' },
      sourcePosition: 'top',
    },
    {
      id: 's-1-1',
      data: { label: 'Data Structures' },
      type: 'output',
      position: { x: 25, y: 122 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
      targetPosition: 'bottom',
    },
    {
      id: 'y-2',
      data: { label: 'Year 2' },
      position: { x: 403, y: 357 },
      style: { backgroundColor: '#587B7F', color: 'white', border: 'none' },
    },
    {
      id: 's-2-1',
      data: { label: 'Problem Solving Techniques' },
      type: 'output',
      position: { x: 239, y: 515 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
    },
    {
      id: 's-2-2',
      data: { label: 'System Program' },
      type: 'input',
      position: { x: 561, y: 236 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
      sourcePosition: 'bottom',
    },
    {
      id: 's-2-3',
      data: { label: 'Algorithm' },
      type: 'input',
      position: { x: 345, y: 219 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
      sourcePosition: 'bottom',
    },
    {
      id: 's-2-4',
      data: { label: 'Introduction to Computer Architectures' },
      type: 'output',
      position: { x: 480, y: 495 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
    },
    {
      id: 'y-3',
      data: { label: 'Year 3' },
      position: { x: 894, y: 480 },
      style: { backgroundColor: '#587B7F', color: 'white', border: 'none' },
    },
    {
      id: 's-3-1',
      data: { label: 'Programming Languages' },
      type: 'output',
      position: { x: 703, y: 609 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
    },
    {
      id: 's-3-2',
      data: { label: 'Introduction to Database' },
      type: 'input',
      position: { x: 747, y: 320 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
      sourcePosition: 'bottom',
    },
    {
      id: 's-3-3',
      data: { label: 'Operating Systems' },
      type: 'input',
      position: { x: 940, y: 275 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
      sourcePosition: 'bottom',
    },
    {
      id: 's-3-4',
      data: { label: 'Introduction to Software Engineering' },
      type: 'output',
      position: { x: 847, y: 718 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
    },
    {
      id: 's-3-5',
      data: { label: 'Introduction to Artificial Intelligence' },
      type: 'output',
      position: { x: 1035, y: 636 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
    },
    {
      id: 's-3-6',
      data: { label: 'Computer Network' },
      type: 'input',
      position: { x: 1086, y: 362 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
      sourcePosition: 'bottom',
    },
    {
      id: 'y-4',
      data: { label: 'Year 4' },
      type: 'input',
      position: { x: 1297, y: 547 },
      style: { backgroundColor: '#587B7F', color: 'white', border: 'none' },
    },
    {
      id: 's-4-1',
      data: { label: 'Fundementals of machine learning' },
      type: 'output',
      position: { x: 1433, y: 664 },
      style: { backgroundColor: '#B8B8B8', color: 'white', border: 'none' },
    },
  ];
  