export default [
    {
      id: 'y-1',
      data: { label: 'Year 1' },
      type: 'year',
      position: { x: 250, y: 25 },
      style: { backgroundColor: '#587B7F', color: 'white' },
    },
    {
      id: 's-1-1',
      data: { label: 'Data Structures' },
      type: 'subject',
      position: { x: 100, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 'y-2',
      data: { label: 'Year 2' },
      type: 'year',
      position: { x: 450, y: 25 },
      style: { backgroundColor: '#587B7F', color: 'white' },
    },
    {
      id: 's-2-1',
      data: { label: 'Problem Solving Techniques' },
      type: 'subject',
      position: { x: 200, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 's-2-2',
      data: { label: 'System Program' },
      type: 'subject',
      position: { x: 300, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 's-2-3',
      data: { label: 'Algorithm' },
      type: 'subject',
      position: { x: 400, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 's-2-4',
      data: { label: 'Introduction to Computer Architectures' },
      type: 'subject',
      position: { x: 500, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 'y-3',
      data: { label: 'Year 3' },
      type: 'year',
      position: { x: 650, y: 25 },
      style: { backgroundColor: '#587B7F', color: 'white' },
    },
    {
      id: 's-3-1',
      data: { label: 'Programming Languages' },
      type: 'subject',
      position: { x: 600, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 's-3-2',
      data: { label: 'Introduction to Database' },
      type: 'subject',
      position: { x: 700, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 's-3-3',
      data: { label: 'Operating Systems' },
      type: 'subject',
      position: { x: 800, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 's-3-4',
      data: { label: 'Introduction to Software Engineering' },
      type: 'subject',
      position: { x: 900, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 's-3-5',
      data: { label: 'Introduction to Artificial Intelligence' },
      type: 'subject',
      position: { x: 1000, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 's-3-6',
      data: { label: 'Computer Network' },
      type: 'subject',
      position: { x: 1100, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
    {
      id: 'y-4',
      data: { label: 'Year 4' },
      type: 'year',
      position: { x: 1150, y: 25 },
      style: { backgroundColor: '#587B7F', color: 'white' },
    },
    {
      id: 's-4-1',
      data: { label: 'Fundementals of machine learning' },
      type: 'subject',
      position: { x: 1200, y: 125 },
      style: { backgroundColor: '#EE4B6A', color: 'white' },
    },
  ];
  